[package]
name = "melda"
version = "0.1.1"
authors = ["Amos Brocco <amos.brocco@supsi.ch>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
yavomrs = { git = "https://github.com/slashdotted/yavomrs.git"}
rust-crypto = "0.2.36"
regex = "1.5.4"
serde_json = "1.0"
serde = "1.0.126"
anyhow = "1.0.41"
url = "2.2.2"
lazy_static = "1.4.0"

# Solid Adapter dependencies
rayon = "1.5.1"
log = "0.4.14"
flate2 = "1.0"
reqwest = { version = "0.11.4", features = ["blocking", "cookies"], optional = true }
rio_api = { version = "0.6.2", optional = true }
rio_turtle = { version = "0.6.2", optional = true }
oxiri = { version = ">=0.1,<0.3", optional = true }
cacache = { version = "8.0.0", optional = true }
lru = { version = "0.6.6", optional = true }

[features]
default = [ "solid" ]
solid =  [ "reqwest", "rio_api", "rio_turtle", "oxiri", "cacache", "lru"]


