[package]
name = "melda"
version = "0.1.0"
authors = ["Amos Brocco <amos.brocco@supsi.ch>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
rust-crypto = "0.2.36"
regex = "1.5.4"
serde_json = "1.0"
serde = "1.0.126"
similar = "1.3.0"
anyhow = "1.0.41"
reqwest = { version = "0.11.4", features = ["blocking", "cookies"] }
rio_api = "0.6.2"
rio_turtle = "0.6.2"
oxiri = ">=0.1,<0.3"
url = "2.2.2"
lazy_static = "1.4.0"
lru = "0.6.6"
cacache = "8.0.0"
rayon = "1.5.1"
log = "0.4.14"
flate2 = "1.0"
